### ISSUE TITLE
Documentation on IAM action `kms:CreateAlias` is missing alias as a resource

### ISSUE THREAD

**Issue by michael-k** [awsdocs/aws-kms-developer-guide#12]
Looking at https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awskeymanagementservice.html#awskeymanagementservice-actions-as-permissions it seems enough to add `arn:${Partition}:kms:${Region}:${Account}:key/${KeyId}` as a resource to an IAM policy.

We tried this within a CloudFormation Stack and it failed:

    User: arn:aws:sts::***:assumed-role/***/AWSCloudFormation
    is not authorized to perform: kms:CreateAlias on resource:
    arn:aws:kms:eu-west-1:***:alias/***

After adding another resource `arn:${Partition}:kms:${Region}:${Account}:alias/${Alias}` everything worked as expected.

I initially reported this as awsdocs/iam-user-guide#119, but was pointed to this repo.

**Comment by juneb** [comment]
Thanks, Michael. The KMS permissions reference[1][2] mentions that you need to specify both a CMK and an alias, and the CloudFormation reference explains how to use an Alias resource[3] in a CloudFormation template. Also, the CreateAlias API requires both a CMK and an alias[4].
 
Is there somewhere else in the KMS Developer Guide that it would be useful to put this information?

[1] https://docs.aws.amazon.com/kms/latest/developerguide/kms-api-permissions-reference.html
[2] https://github.com/awsdocs/aws-kms-developer-guide/blob/master/doc_source/kms-api-permissions-reference.md 
[3] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-alias.html
[4] https://docs.aws.amazon.com/kms/latest/APIReference/API_CreateAlias.html

**Comment by michael-k** [comment]
I'm not familiar with enough with the KMS documentation to answer this.  I especially care about the actions tables in the IAM documentation.  It's what I use to write Policies at work, find missing actions in awacs (see eg. cloudtools/awacs#115) and it also seems to be what others refer to (see eg. https://iam.cloudonaut.io/).

The most helpful feature however would be if the [CloudFormation Linter](https://github.com/aws-cloudformation/cfn-python-lint) would catch those errors.  I thought about writing such a rule, but haven't had the time and I would base it on IAM's documentation anyway.

**Comment by juneb** [comment]
That makes perfect sense. Let me see what KMS needs to do to update the IAM doc page. Thanks again for reporting this.

**Comment by juneb** [comment]
I'm trying to track this down. Can you please confirm that you used an Alias **resource** in a CloudFormation template to **create** an alias? That should work only if you are updating an alias in your CloudFormation stack. Otherwise, the key is the input resource and the alias is the returned/created resource.  

The KMS **Alias** resource topic in the CloudFormation reference shows an example of creating an alias in a CloudFormation template:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-alias.html

The CreateAlias API table entry in the IAM KMS topic (https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awskeymanagementservice.html#awskeymanagementservice-actions-as-permissions) lists a key resource, because that is the only **resource** that you need to provide to create an alias. You also need to provide an **alias name**, but not an alias resource.

**Comment by juneb** [comment]
Michael, we tracked this down. 

As explained in the KMS Developer Guide (https://docs.aws.amazon.com/kms/latest/developerguide/kms-api-permissions-reference.html), 
CreateAlias requires permissions on the CMK in a key policy and an alias in the IAM policy. 

We need to fix the IAM page and explain how this works in the KMS docs. 

I'm going to leave this issue open until we have a resolution.

**Comment by juneb** [comment]
Closing this issue with a resolution:
We added a new section to the KMS docs that explains that CreateAlias and DeleteAlias require permission on the CMK and the alias. UpdateAlias requires permission on the alias and both the source and destination CMKs. 
https://github.com/awsdocs/aws-kms-developer-guide/blob/master/doc_source/kms-alias.md#alias-access
