### ISSUE TITLE
Examples in multiple programming languages 

### ISSUE THREAD

**Issue by juneb** [awsdocs/aws-kms-developer-guide#5]
The [Programming the AWS KMS API](https://github.com/awsdocs/aws-kms-developer-guide/blob/master/doc_source/programming-top.md) section of the AWS KMS developer guide now has examples in Java, C#, Python, Ruby, PHP, and Node.js. We'd love to have examples in other languages. 

When submitting your examples, please be sure to make them analogous to the existing example, but idiomatic to the language. If you have questions, ask them in this issue.

Thanks in advance for your contribution!

**Comment by cwgem** [comment]
I would mention that the way the examples are structured it's extremely easy to merge conflict. For example, #7 's merge means #6 's won't merge because it's all the same file. I'm not sure what you have for building docs but if each doc with multi-language code had its own dedicated folder with individual files I think that would help greatly. For example:

```
doc_source/programming-aliases.md
doc_source/programming-aliases/
doc_source/programming-aliases-examples/node.md
doc_source/programming-aliases-examples/php.md
```

Then when the build system hit `programming-aliases.md` there would be some kind of templating logic that would iterate through each of the entries and write them out. You could even add some metadata to the example Markdown files for labels/descriptions/etc.

**Comment by juneb** [comment]
Thanks, Chris. Good point. Unfortunately, I don't have that flexibility in our current system.

**Comment by matteofigus** [comment]
@cwgem I made #6 mergeable again, hope it helps.
